// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.0
// source: go_db_proxy.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JStatementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query  string  `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Params []byte  `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Dates  []int32 `protobuf:"varint,3,rep,packed,name=dates,proto3" json:"dates,omitempty"`
	Tx     string  `protobuf:"bytes,4,opt,name=tx,proto3" json:"tx,omitempty"`
	Master string  `protobuf:"bytes,5,opt,name=master,proto3" json:"master,omitempty"`
	Commit string  `protobuf:"bytes,6,opt,name=commit,proto3" json:"commit,omitempty"`
}

func (x *JStatementRequest) Reset() {
	*x = JStatementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_db_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JStatementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JStatementRequest) ProtoMessage() {}

func (x *JStatementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_db_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JStatementRequest.ProtoReflect.Descriptor instead.
func (*JStatementRequest) Descriptor() ([]byte, []int) {
	return file_go_db_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *JStatementRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *JStatementRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *JStatementRequest) GetDates() []int32 {
	if x != nil {
		return x.Dates
	}
	return nil
}

func (x *JStatementRequest) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

func (x *JStatementRequest) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

func (x *JStatementRequest) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

type JStatementBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Batch  []*JStatementRequest `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"`
	Tx     string               `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	Master string               `protobuf:"bytes,3,opt,name=master,proto3" json:"master,omitempty"`
	Commit string               `protobuf:"bytes,4,opt,name=commit,proto3" json:"commit,omitempty"`
}

func (x *JStatementBatchRequest) Reset() {
	*x = JStatementBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_db_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JStatementBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JStatementBatchRequest) ProtoMessage() {}

func (x *JStatementBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_db_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JStatementBatchRequest.ProtoReflect.Descriptor instead.
func (*JStatementBatchRequest) Descriptor() ([]byte, []int) {
	return file_go_db_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *JStatementBatchRequest) GetBatch() []*JStatementRequest {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *JStatementBatchRequest) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

func (x *JStatementBatchRequest) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

func (x *JStatementBatchRequest) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

type JStatementBatchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result  int64  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *JStatementBatchReply) Reset() {
	*x = JStatementBatchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_db_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JStatementBatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JStatementBatchReply) ProtoMessage() {}

func (x *JStatementBatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_go_db_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JStatementBatchReply.ProtoReflect.Descriptor instead.
func (*JStatementBatchReply) Descriptor() ([]byte, []int) {
	return file_go_db_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *JStatementBatchReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JStatementBatchReply) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type JStatementReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Details int64  `protobuf:"varint,2,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *JStatementReply) Reset() {
	*x = JStatementReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_db_proxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JStatementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JStatementReply) ProtoMessage() {}

func (x *JStatementReply) ProtoReflect() protoreflect.Message {
	mi := &file_go_db_proxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JStatementReply.ProtoReflect.Descriptor instead.
func (*JStatementReply) Descriptor() ([]byte, []int) {
	return file_go_db_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *JStatementReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JStatementReply) GetDetails() int64 {
	if x != nil {
		return x.Details
	}
	return 0
}

type BeginTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timeout int64 `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *BeginTransactionRequest) Reset() {
	*x = BeginTransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_db_proxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionRequest) ProtoMessage() {}

func (x *BeginTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_db_proxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionRequest.ProtoReflect.Descriptor instead.
func (*BeginTransactionRequest) Descriptor() ([]byte, []int) {
	return file_go_db_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *BeginTransactionRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type BeginTransactionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BeginTransactionReply) Reset() {
	*x = BeginTransactionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_db_proxy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginTransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionReply) ProtoMessage() {}

func (x *BeginTransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_go_db_proxy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionReply.ProtoReflect.Descriptor instead.
func (*BeginTransactionReply) Descriptor() ([]byte, []int) {
	return file_go_db_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *BeginTransactionReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EndTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx       string `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	Rollback string `protobuf:"bytes,2,opt,name=rollback,proto3" json:"rollback,omitempty"`
}

func (x *EndTransactionRequest) Reset() {
	*x = EndTransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_db_proxy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndTransactionRequest) ProtoMessage() {}

func (x *EndTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_db_proxy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndTransactionRequest.ProtoReflect.Descriptor instead.
func (*EndTransactionRequest) Descriptor() ([]byte, []int) {
	return file_go_db_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *EndTransactionRequest) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

func (x *EndTransactionRequest) GetRollback() string {
	if x != nil {
		return x.Rollback
	}
	return ""
}

type EndTransactionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *EndTransactionReply) Reset() {
	*x = EndTransactionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_db_proxy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndTransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndTransactionReply) ProtoMessage() {}

func (x *EndTransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_go_db_proxy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndTransactionReply.ProtoReflect.Descriptor instead.
func (*EndTransactionReply) Descriptor() ([]byte, []int) {
	return file_go_db_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *EndTransactionReply) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_go_db_proxy_proto protoreflect.FileDescriptor

var file_go_db_proxy_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x6f, 0x5f, 0x64, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x11,
	0x4a, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x74, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x22, 0x89, 0x01, 0x0a, 0x16, 0x4a, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2f, 0x0a, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e, 0x4a, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05, 0x62, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74,
	0x78, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x22, 0x48, 0x0a, 0x14, 0x4a, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x45, 0x0a, 0x0f, 0x4a,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x22, 0x33, 0x0a, 0x17, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x27, 0x0a, 0x15, 0x42, 0x65, 0x67, 0x69, 0x6e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x43, 0x0a, 0x15, 0x45, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x22, 0x31, 0x0a, 0x13, 0x45, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xfe, 0x02, 0x0a, 0x09, 0x47, 0x6f, 0x44,
	0x62, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x3d, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12,
	0x19, 0x2e, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e, 0x4a, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6f, 0x72, 0x61,
	0x63, 0x6c, 0x65, 0x2e, 0x4a, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x12, 0x19, 0x2e, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e, 0x4a, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6f, 0x72,
	0x61, 0x63, 0x6c, 0x65, 0x2e, 0x4a, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x09, 0x45, 0x78, 0x65, 0x63, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x1e, 0x2e, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e, 0x4a, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e, 0x4a, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x10, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65,
	0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6f, 0x72, 0x61, 0x63, 0x6c,
	0x65, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0e, 0x45, 0x6e, 0x64,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x6f, 0x72,
	0x61, 0x63, 0x6c, 0x65, 0x2e, 0x45, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6f, 0x72, 0x61,
	0x63, 0x6c, 0x65, 0x2e, 0x45, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x6f, 0x2d,
	0x64, 0x62, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_go_db_proxy_proto_rawDescOnce sync.Once
	file_go_db_proxy_proto_rawDescData = file_go_db_proxy_proto_rawDesc
)

func file_go_db_proxy_proto_rawDescGZIP() []byte {
	file_go_db_proxy_proto_rawDescOnce.Do(func() {
		file_go_db_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_go_db_proxy_proto_rawDescData)
	})
	return file_go_db_proxy_proto_rawDescData
}

var file_go_db_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_go_db_proxy_proto_goTypes = []interface{}{
	(*JStatementRequest)(nil),       // 0: oracle.JStatementRequest
	(*JStatementBatchRequest)(nil),  // 1: oracle.JStatementBatchRequest
	(*JStatementBatchReply)(nil),    // 2: oracle.JStatementBatchReply
	(*JStatementReply)(nil),         // 3: oracle.JStatementReply
	(*BeginTransactionRequest)(nil), // 4: oracle.BeginTransactionRequest
	(*BeginTransactionReply)(nil),   // 5: oracle.BeginTransactionReply
	(*EndTransactionRequest)(nil),   // 6: oracle.EndTransactionRequest
	(*EndTransactionReply)(nil),     // 7: oracle.EndTransactionReply
}
var file_go_db_proxy_proto_depIdxs = []int32{
	0, // 0: oracle.JStatementBatchRequest.batch:type_name -> oracle.JStatementRequest
	0, // 1: oracle.GoDbProxy.Query:input_type -> oracle.JStatementRequest
	0, // 2: oracle.GoDbProxy.Execute:input_type -> oracle.JStatementRequest
	1, // 3: oracle.GoDbProxy.ExecBatch:input_type -> oracle.JStatementBatchRequest
	4, // 4: oracle.GoDbProxy.BeginTransaction:input_type -> oracle.BeginTransactionRequest
	6, // 5: oracle.GoDbProxy.EndTransaction:input_type -> oracle.EndTransactionRequest
	3, // 6: oracle.GoDbProxy.Query:output_type -> oracle.JStatementReply
	3, // 7: oracle.GoDbProxy.Execute:output_type -> oracle.JStatementReply
	2, // 8: oracle.GoDbProxy.ExecBatch:output_type -> oracle.JStatementBatchReply
	5, // 9: oracle.GoDbProxy.BeginTransaction:output_type -> oracle.BeginTransactionReply
	7, // 10: oracle.GoDbProxy.EndTransaction:output_type -> oracle.EndTransactionReply
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_go_db_proxy_proto_init() }
func file_go_db_proxy_proto_init() {
	if File_go_db_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_go_db_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JStatementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_db_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JStatementBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_db_proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JStatementBatchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_db_proxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JStatementReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_db_proxy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginTransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_db_proxy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeginTransactionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_db_proxy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndTransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_go_db_proxy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndTransactionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_go_db_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_db_proxy_proto_goTypes,
		DependencyIndexes: file_go_db_proxy_proto_depIdxs,
		MessageInfos:      file_go_db_proxy_proto_msgTypes,
	}.Build()
	File_go_db_proxy_proto = out.File
	file_go_db_proxy_proto_rawDesc = nil
	file_go_db_proxy_proto_goTypes = nil
	file_go_db_proxy_proto_depIdxs = nil
}
